server:
  port: 8761

spring:
  application:
    name: springboot-conf-eureka-server
    
eureka:
  client:
    eureka-server-connect-timeout-seconds: 5
    enabled: true
    fetch-registry: false
    register-with-eureka: false
    log-delta-diff: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  # --> Include git.properties generated informations (plugin:git-commit-id-plugin) in /actuator/info endpoint.
  info:
    git:
      mode: full