server:
  port: 8761

spring:
  application:
    name: springboot-conf-eureka-server
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    driver-class-name: org.postgresql.Driver
    username: ${database.username}
    password: ${database.password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool_EUREKA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: none
    show-sql: false

database:
  host: 10.0.0.137
  port: 5432
  name: postgres_data_source
  username: postgres_data_source
  password: postgres_data_source


eureka:
  client:
    eureka-server-connect-timeout-seconds: 5
    enabled: true
    fetch-registry: false
    register-with-eureka: false
    log-delta-diff: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  # --> Include git.properties generated informations (plugin:git-commit-id-plugin) in /actuator/info endpoint.
  info:
    git:
      mode: full